feat: gatewayservice의 create, join할 때 해싱된 비밀번호 검증로직 추가
42-pingpong/backend pull request #119
Opened 2023-08-16 09:32 UTC by gyuminv2

2023-08-16 09:34 UTC, gyuminv2 commented
형 부족한부분 코멘트달아주세여 @koreanddinghwan

2023-08-16 15:09 UTC, koreanddinghwan requested changes

2023-08-16 15:09 UTC, koreanddinghwan commented on package.json
> +    "bcrypt": "^5.1.1",
npm i --save-dev @types/bcript

2023-08-16 15:09 UTC, koreanddinghwan commented on src/restapi/chat/chat.service.ts
> +    const hashedPassword = await bcrypt.hash(createChatDto.password, 10);
salt 추가

2023-08-16 17:11 UTC, koreanddinghwan approved these changes, later dismissed

2023-08-16 17:11 UTC, koreanddinghwan commented on src/restapi/chat/chat.service.ts
> +    const hashedPassword = await bcrypt.hash(createChatDto.password, 10);
는 알아서 해주는구나

2023-08-16 17:11 UTC, koreanddinghwan commented on package.json
> +    "bcrypt": "^5.1.1",
이것만 추가해주쇼

2023-08-19 18:55 UTC, koreanddinghwan approved these changes

2023-08-19 18:55 UTC, merged