Feature/restapi/chat
42-pingpong/backend pull request #38
Opened 2023-08-03 07:50 UTC by gyuminv2

delete test

2023-08-03 09:15 UTC, koreanddinghwan requested changes

2023-08-03 09:15 UTC, koreanddinghwan commented on test/chat/chat.e2e-spec.ts
> +      // 형 채팅방 이름도 수정 가능해야하지 않나요?
test: 
권한 박탈당하는 사람 예외처리
1. admin권한 뺏으려는 유저가 채팅방 owner인경우
2. admin권한 뺏으려는 유저가 채팅방에 없는경우

권한 박탈하는 사람 예외처리
3. admin권한 뺏는 유저가 권한이 없는경우
4. admin권한 뺏는 유저가 없는경우

에 대해서 고려되어있나?

2023-08-03 09:15 UTC, koreanddinghwan commented on test/chat/chat.e2e-spec.ts
> +      // 형 채팅방 이름도 수정 가능해야하지 않나요?
에 대해 생각해보면 좋을듯

2023-08-03 09:15 UTC, koreanddinghwan commented on test/chat/chat.e2e-spec.ts
> +      // 형 채팅방 이름도 수정 가능해야하지 않나요?
쿼리가 복잡하면 테스트코드 다양하게 만들어놔야 나중에 편해

2023-08-03 09:16 UTC, koreanddinghwan requested changes

2023-08-03 09:16 UTC, koreanddinghwan commented on test/chat/chat.e2e-spec.ts
> +    // it.todo('POST /api/chat/groupChat/:groupChatId/admin');
어드민 추가도 동일함

2023-08-03 11:43 UTC, gyuminv2 commented on test/chat/chat.e2e-spec.ts
> +      // 형 채팅방 이름도 수정 가능해야하지 않나요?
생각해볼게요

2023-08-03 12:56 UTC, koreanddinghwan requested changes

2023-08-03 12:56 UTC, koreanddinghwan commented on test/chat/chat.e2e-spec.ts
> +
https://github.com/42-pingpong/backend/blob/ecd8e9c19929d370ce8728fc39cbf800a9d6925e/test/user/user.e2e-spec.ts#L397-L482

2023-08-03 12:56 UTC, koreanddinghwan commented on test/chat/chat.e2e-spec.ts
> +
이런식으로

2023-08-03 16:20 UTC, gyuminv2 commented on test/chat/chat.e2e-spec.ts
> +
형 그러면 service함수 자체도 수정해줘야하는데 test수정 -> service수정 이런식으로 하면 되는거에요?

2023-08-03 17:08 UTC, koreanddinghwan commented on test/chat/chat.e2e-spec.ts
> +
서비스를 수정해야한다는게 구체적으로 모야? 설명점

2023-08-03 17:11 UTC, gyuminv2 commented on test/chat/chat.e2e-spec.ts
> +
만약에 test에서 404를 뱉도록 기대하는 로직이면요, service에서도 똑같은 상황일때 404를 뱉어야하는게아닌가여? 라는 말입니다

2023-08-03 17:45 UTC, koreanddinghwan commented on test/chat/chat.e2e-spec.ts
> +
반대로 생각해야지 
저 테스트들은 일부러 터지는 케이스들을 넣는거고 그 케이스들에 대해서 에러핸들링이 적절하게 되고있나를 검증하는거여
터지는 케이스를 먼저 정의 => 코드를 터지는 케이스에서 적절한 에러처리하도록 수정 => 테스트 => 안되면 코드수정 => 테스트 이거 반복

2023-08-03 17:46 UTC, koreanddinghwan commented on test/chat/chat.e2e-spec.ts
> +
.send나 .query같은걸로 dto넣을때 에러처리 잘 되게하려면 일부러 인자 이상한것도 넣으면서 테스트하는거지

2023-08-03 17:46 UTC, koreanddinghwan commented on test/chat/chat.e2e-spec.ts
> +
controller/service단에서 유닛테스트를 지금 여기서 하고있다고 생각혀

2023-08-04 04:41 UTC, koreanddinghwan commented on test/chat/chat.e2e-spec.ts
> -      const response = await request(app.getHttpServer()).post(
엉

2023-08-04 08:57 UTC, koreanddinghwan approved these changes, later dismissed
굳굳 이런식으로하면됨!

2023-08-04 15:24 UTC, koreanddinghwan approved these changes

2023-08-04 15:24 UTC, merged