Feat game
42-pingpong/backend pull request #78
Opened 2023-08-10 10:38 UTC by gyuminv2

game관련해서 gateway.service로직 짰습니다

2023-08-10 10:59 UTC, koreanddinghwan requested changes

2023-08-10 10:59 UTC, koreanddinghwan commented on src/sockets/game/game.gateway.servcie.ts
> +        Authorization: `Bearer ${bearerToken}`,
bearerToken만 써야할거같은디 저거 자체에 들어가있을걸?

2023-08-10 13:13 UTC, gyuminv2 commented on src/sockets/game/game.gateway.servcie.ts
> +        Authorization: `Bearer ${bearerToken}`,
넵 확인해보고 수정할게요

2023-08-10 14:23 UTC, koreanddinghwan commented on src/sockets/game/game.gateway.servcie.ts
> +        Authorization: `Bearer ${bearerToken}`,
오케이

2023-08-12 12:04 UTC, koreanddinghwan commented on src/restapi/game/request/create-game.dto.ts
> -  createDate: Date;
ㅇㅇ...직접넣으면안됌..

2023-08-12 12:10 UTC, gyuminv2 commented on src/restapi/game/request/create-game.dto.ts
> -  createDate: Date;
요놈때문에 ....

2023-08-16 08:24 UTC, koreanddinghwan requested changes

2023-08-16 08:24 UTC, koreanddinghwan commented on src/sockets/game/game.gateway.servcie.ts
> +        Authorization: `Bearer ${bearerToken}`,
저거 컨트롤러에서 지금은 auth check를 안하고 있어서 오류 안터지는데, auth check하면 터질거임

2023-08-16 08:24 UTC, koreanddinghwan commented on src/sockets/game/game.gateway.servcie.ts
> +        Authorization: `Bearer ${bearerToken}`,
상동

2023-08-16 08:24 UTC, koreanddinghwan commented on src/sockets/game/game.gateway.servcie.ts
> +        Authorization: `Bearer ${bearerToken}`,
상동

2023-08-21 16:13 UTC, closed without merging